GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY0NzEyMTY2fQ.2nijbduVMR2pXCRdptR3mWM9KAPBbLghRhXOT0_33x4

###
GET http://localhost:8080/api/v1/users/1
Accept: application/json

### SUCCESS
POST http://localhost:8080/api/v1/registration
Content-Type: application/json

{
    "email": "me40@live.com.sg",
    "username": "xiaodidi",
    "password": "baby123!"
}

### FAIL USERNAME TAKEN
POST http://localhost:8080/api/v1/registration
Content-Type: application/json

{
    "email": "me4033@gmail.com",
    "username": "xiaodidi",
    "password": "baby123!"
}

### CONFIRM REGISTRATION TOKEN
GET http://localhost:8080/api/v1/registration/confirm?token=cf45741b-2070-40d3-8523-fd7008d91106

### LOGIN (SUCCESS)
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "username": "xiaodidi",
    "password": "baby123!"
}

### LOGIN (FAIL INVALID USERNAME)
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "username": "xiaomama",
    "password": "baby123!"
}

### LOGIN (FAIL INVALID PASSWORD)
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "username": "xiaodidi",
    "password": "wrongpassword"
}


### FORGET PASSWORD
POST http://localhost:8080/api/v1/forget-password
Content-Type: application/json

{
    "email": "me40@live.com.sg"
}

### RESET PASSWORD (SUCCESS)
PUT http://localhost:8080/api/v1/forget-password/reset?token=03a488c7-98a4-41e1-8fa4-ed3c649375cf
Content-Type: application/json

{
    "newPassword": "iLoveSpringBoot",
    "confirmNewPassword": "iLoveSpringBoot"
}

### RESET PASSWORD (PasswordNotMatchingException)
PUT http://localhost:8080/api/v1/forget-password/reset?token=03a488c7-98a4-41e1-8fa4-ed3c649375cf
Content-Type: application/json

{
    "newPassword": "iLoveSpringBoot",
    "confirmNewPassword": "iHateSpringBoot"
}