### NEW FOOD
POST http://localhost:8080/api/v1/food
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0ODA4MzR9.D7skhKD5vzLFToUWN-wbGBjhn-BEmZtDa1oL_2pRpbM
Content-Type: application/json

{
    "foodName": "Milk",
    "category": "dairy"
}

### GET FOOD
GET http://localhost:8080/api/v1/food/Milk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0ODA4MzR9.D7skhKD5vzLFToUWN-wbGBjhn-BEmZtDa1oL_2pRpbM
Accept: application/json

### GET STORAGE
POST http://localhost:8080/api/v1/xiaodidi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0ODYxMDd9.QwnF8l4yL2T7SAtd3Ash8tBwjxeQOcRIJhQm4EFpTIs


### GET FOOD
GET http://localhost:8080/api/v1/food/Milk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0ODA4MzR9.D7skhKD5vzLFToUWN-wbGBjhn-BEmZtDa1oL_2pRpbM
Accept: application/json


### NEW CONTAINER
POST http://localhost:8080/api/v1/containers/xiaodidi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0OTg3NDd9._77tU8xYnJAoDr7UngWuzjRG098aL61k2c6IiAnlbcE
Content-Type: application/json

{
    "capacity": "6.0",
    "i": "3",
    "j": "1"
}

### GET ALL CONTAINERS (FOR RENDERING UPON LOGIN)
GET http://localhost:8080/api/v1/containers/xiaodidi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0OTg3NDd9._77tU8xYnJAoDr7UngWuzjRG098aL61k2c6IiAnlbcE
Accept: application/json


### GET SPECIFIC CONTAINER (IF WE WANNA EDIT STH)
GET http://localhost:8080/api/v1/containers/xiaodidi/3_1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0OTg3NDd9._77tU8xYnJAoDr7UngWuzjRG098aL61k2c6IiAnlbcE
Accept: application/json

### NEW BLOCK
POST http://localhost:8080/api/v1/blocks/xiaodidi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc1MDE3Nzl9.7JYSli1QscR-EQyAEKmGGoV8dFl2i6cfydFweCi_CTc
Content-Type: application/json

{
    "i": "3",
    "j": "3"
}

### GET ALL BLOCKS
GET http://localhost:8080/api/v1/blocks/xiaodidi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc1MDE3Nzl9.7JYSli1QscR-EQyAEKmGGoV8dFl2i6cfydFweCi_CTc
Accept: application/json

### GET SPECIFIC BLOCK
GET http://localhost:8080/api/v1/blocks/xiaodidi/3_3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc1MDE3Nzl9.7JYSli1QscR-EQyAEKmGGoV8dFl2i6cfydFweCi_CTc
Accept: application/json