GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY1MzgzNjU3fQ.pYBsRbeaao0ftGdz7PdPZCwAZ70S-xTIZvQx8n2Enms

###
GET http://localhost:8080/api/v1/users/1
Accept: application/json

### REGISTER SUCCESS (USER)
POST http://localhost:8080/api/v1/registration
Content-Type: application/json

{
    "email": "me40@live.com.sg",
    "username": "xiaodidi",
    "password": "baby123!"
}

### REGISTER SUCCESS (ADMIN)
POST http://localhost:8080/api/v1/registration
Content-Type: application/json

{
    "email": "me4033@gmail.com",
    "username": "littleboi",
    "password": "baby123!",
    "authorities": "ROLE_ADMIN"
}

### CONFIRM REGISTRATION TOKEN
GET http://localhost:8080/api/v1/registration/confirm?token=374dacaa-0f10-4630-a83b-94bcfd279e71

### LOGIN (SUCCESS)
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "username": "xiaodidi",
    "password": "12345"
}

### LOGIN (FAIL INVALID USERNAME)
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "username": "xiaomama",
    "password": "baby123!"
}

### LOGIN (FAIL INVALID PASSWORD)
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "username": "xiaodidi",
    "password": "wrongpassword"
}


### FORGET PASSWORD
POST http://localhost:8080/api/v1/forget-password
Content-Type: application/json

{
    "email": "me40@live.com.sg"
}

### RESET PASSWORD (SUCCESS)
PUT http://localhost:8080/api/v1/forget-password/reset?token=d1f268e6-9a09-45c0-a286-27e5b6c2b7d1
Content-Type: application/json

{
    "newPassword": "iLoveSpringBoot",
    "confirmNewPassword": "iLoveSpringBoot"
}

### RESET PASSWORD (PasswordNotMatchingException)
PUT http://localhost:8080/api/v1/forget-password/reset?token=1f06f98d-9fac-44ad-b2ab-0143946b41ec
Content-Type: application/json

{
    "newPassword": "iLoveSpringBoot",
    "confirmNewPassword": "iHateSpringBoot"
}




### GET FOOD 
GET http://localhost:8080/api/v1/food/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY2MDEzNjk0fQ.kKT7iUBb5SU3AoRYySnvtq5gGndwH5I7T88lhTVE8oE
Accept: application/json
Content-Type: application/json

{
    "foodName": "Milk"
}

### NEW FOOD
POST http://localhost:8080/api/v1/food
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2NjYwNjIyMjl9.oM78ifqhsKoBpcPycoCugoUbVe9P4z54Alca60adfWU
Content-Type: application/json

{
    "foodName": "Milk",
    "category": "dairy",
    "currentQuantity": "2.5"
}

### UPDATE FOOD
PUT http://localhost:8080/api/v1/food/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY2MDE2NTk5fQ.8i33wtnidwN3JfwBQySdyxUKLtMwBOA9tx6cFpm8YlY
Content-Type: application/json

{
    "foodName": "Milk",
    "category": "dairy",
    "currentQuantity": "4"
}

### DELETE FOOD
DELETE http://localhost:8080/api/v1/food/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY1ODExNTEyfQ.vphoDo1FjNXRADLxsvFDR0Maza048uGSXESpBhO8gxU

### GET FOOD 
GET http://localhost:8080/api/v1/food
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY2MDEzNjk0fQ.kKT7iUBb5SU3AoRYySnvtq5gGndwH5I7T88lhTVE8oE





### NEW PURCHASE
POST http://localhost:8080/api/v1/food/1/purchases
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2NjYwMjE0Mzd9.C3pQcsCVFpCe0oeTxp3Mylk5foGWpV3KGtHSwXYzWEY
Content-Type: application/json

{
    "dateBought": "2022-10-07",
    "amountBought": "3",
    "expiryDate": "2022-11-07",
    "foodId": "1"
}

### UPDATE PURCHASE
PUT http://localhost:8080/api/v1/food/1/purchases/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2NjYwMjExNzR9.m5ggV0j7F2taIOSke30l8XLOyTWfuJMmJz03CoAt8mY
Content-Type: application/json

{
    "purchaseId" : "1",
    "dateBought": "2022-10-07",
    "amountBought": "5",
    "expiryDate": "2022-11-10",
    "foodId": "1"
}


### DELETE PURCHASE
DELETE http://localhost:8080/api/v1/purchases/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY1MTExMzU3fQ.pYszOHmQAFvbkPl_0jPWEIdNEWNe3BpMcxzrbcXJoME






### NEW CONSUMPTION
POST http://localhost:8080/api/v1/food/1/consumptions
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2NjYwMTg2MTl9.kGfNjPUayWLlSc07BRW3yHXGHGxBwLiclqTfnw2qRTw
Content-Type: application/json

{
    "dateConsumed": "2022-10-15",
    "amountConsumed": "2",
    "foodId": "1"
}


### UPDATE CONSUMPTION
PUT http://localhost:8080/api/v1/food/1/consumptions/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2NjYwMTg2MTl9.kGfNjPUayWLlSc07BRW3yHXGHGxBwLiclqTfnw2qRTw
Content-Type: application/json

{
    "consumptionId" : "1",
    "dateConsumed": "2022-10-15",
    "amountConsumed": "1",
    "foodId": "1"
}


### DELETE CONSUMPTION
DELETE http://localhost:8080/api/v1/food/1/consumptions/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY1ODEzMzI1fQ.Ghgr0vS8AV_nUlVD2pDw8DLB6s0Wn356NzGjBBikJM4

### CHECK USERNAME EXISTS
POST http://localhost:8080/api/v1/users/check-username
Content-Type: application/json

{
    "username": "xiaodidi",
    "password": ""
}


### NEW CONTAINER
POST http://localhost:8080/api/v1/food/1/containers
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2NjYwNjIyMjl9.oM78ifqhsKoBpcPycoCugoUbVe9P4z54Alca60adfWU
Content-Type: application/json

{
    "capacity": "25",
    "threshold": "5",
    "rowIndex": "2",
    "colIndex" : "3"
}

### UPDATE CONTAINER
PUT http://localhost:8080/api/v1/food/1/containers/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoibG9jYWxob3N0OjgwODAvYXBpL3YxL2xvZ2luIiwiZXhwIjoxNjY2MDE1OTEyfQ.Poic8G1MY5XAziUFAjeMSCOnghY59fk889mjizkKcwo
Content-Type: application/json

{
    "capacity" : "50",
    "threshold" : "25"
}