### NEW FOOD
POST http://localhost:8080/api/v1/food
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0ODA4MzR9.D7skhKD5vzLFToUWN-wbGBjhn-BEmZtDa1oL_2pRpbM
Content-Type: application/json

{
    "foodName": "Milk",
    "category": "dairy"
}

### GET FOOD
GET http://localhost:8080/api/v1/food/Milk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0ODA4MzR9.D7skhKD5vzLFToUWN-wbGBjhn-BEmZtDa1oL_2pRpbM
Accept: application/json

### GET STORAGE
POST http://localhost:8080/api/v1/xiaodidi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0ODYxMDd9.QwnF8l4yL2T7SAtd3Ash8tBwjxeQOcRIJhQm4EFpTIs


### GET FOOD
GET http://localhost:8080/api/v1/food/Milk
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0ODA4MzR9.D7skhKD5vzLFToUWN-wbGBjhn-BEmZtDa1oL_2pRpbM
Accept: application/json


### NEW CONTAINER
POST http://localhost:8080/api/v1/containers/xiaodidi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0OTUxMjZ9.UuoZYjyxa8TVsjnTslmaJvOgXXBHoE_weY2R_X-jxjI
Content-Type: application/json

{
    "capacity": "6.0",
    "i": "3",
    "j": "1"
}

### GET ALL CONTAINERS (FOR RENDERING UPON LOGIN)
GET http://localhost:8080/api/v1/containers/xiaodidi
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0OTUxMjZ9.UuoZYjyxa8TVsjnTslmaJvOgXXBHoE_weY2R_X-jxjI
Accept: application/json


### GET SPECIFIC CONTAINER (IF WE WANNA EDIT STH)
GET http://localhost:8080/api/v1/containers/xiaodidi/2_1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ4aWFvZGlkaSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJpc3MiOiJsb2NhbGhvc3Q6ODA4MC9hcGkvdjEvbG9naW4iLCJleHAiOjE2Njc0OTI3NTR9.NNyVjean1TV656jpvKuvFG_5Lc83pSWSnQdODCBfVKA
Accept: application/json